export const ENEMY_SPAWNS_ENABLED = true,
  ENEMY_SPAWN_TIME = 4000,
  MAPWIDTH = 800,
  MAPHEIGHT = 480,
  MAPCENTERX = MAPWIDTH / 2,
  MAPCENTERY = MAPHEIGHT / 2,
  SPAWN = { x: MAPCENTERX, y: MAPCENTERY + 100 };
